tab_spaces = 2
fn_single_line = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
trailing_comma = "Never"
use_field_init_shorthand = true
unstable_features = true